modLoader="fabric"
loaderVersion="[0.14.0,)"
modId="fabric-mobile-performance-mod"
version="1.0.0"
displayName="Fabric Mobile Performance Mod"
description="A mod aimed at improving performance for mobile devices using PojavLauncher."
authors="YourName"
contact="your.email@example.com"

[[dependencies]]
modId="fabric-api"
version="[0.50.0,)"